import { ASSET_KEYS } from '../assets/manifest.js';

export const ENEMY_DEFINITIONS = Object.freeze({
  dustMite: Object.freeze({
    id: 'dustMite',
    name: 'Dust Mite',
    maxHp: 24,
    speed: 92,
    reward: 5,
    stationDamage: 2,
    assetKey: ASSET_KEYS.enemies.dustMite,
  }),
  rustRunner: Object.freeze({
    id: 'rustRunner',
    name: 'Rust Runner',
    maxHp: 42,
    speed: 138,
    reward: 8,
    stationDamage: 4,
    assetKey: ASSET_KEYS.enemies.rustRunner,
  }),
  tinbackHauler: Object.freeze({
    id: 'tinbackHauler',
    name: 'Tinback Hauler',
    maxHp: 140,
    speed: 56,
    reward: 16,
    stationDamage: 9,
    assetKey: ASSET_KEYS.enemies.tinbackHauler,
  }),
  sparkWagon: Object.freeze({
    id: 'sparkWagon',
    name: 'Spark Wagon',
    maxHp: 96,
    speed: 66,
    reward: 14,
    stationDamage: 7,
    assetKey: ASSET_KEYS.enemies.sparkWagon,
  }),
  riftLeech: Object.freeze({
    id: 'riftLeech',
    name: 'Rift Leech',
    maxHp: 82,
    speed: 76,
    reward: 13,
    stationDamage: 6,
    assetKey: ASSET_KEYS.enemies.riftLeech,
  }),
  siegeCrawler: Object.freeze({
    id: 'siegeCrawler',
    name: 'Siege Crawler',
    maxHp: 210,
    speed: 44,
    reward: 22,
    stationDamage: 14,
    assetKey: ASSET_KEYS.enemies.siegeCrawler,
  }),
  blackComet: Object.freeze({
    id: 'blackComet',
    name: 'The Black Comet',
    maxHp: 1400,
    speed: 34,
    reward: 200,
    stationDamage: 100,
    assetKey: ASSET_KEYS.enemies.blackComet,
  }),
});
