import { ASSET_KEYS } from '../assets/manifest.js';

export const ENEMY_DEFINITIONS = Object.freeze({
  dustMite: Object.freeze({
    id: 'dustMite',
    name: 'Dust Mite',
    maxHp: 28,
    speed: 92,
    reward: 5,
    stationDamage: 2,
    assetKey: ASSET_KEYS.enemies.dustMite,
  }),
  rustRunner: Object.freeze({
    id: 'rustRunner',
    name: 'Rust Runner',
    maxHp: 48,
    speed: 138,
    reward: 8,
    stationDamage: 4,
    assetKey: ASSET_KEYS.enemies.rustRunner,
  }),
  tinbackHauler: Object.freeze({
    id: 'tinbackHauler',
    name: 'Tinback Hauler',
    maxHp: 148,
    speed: 56,
    reward: 16,
    stationDamage: 9,
    assetKey: ASSET_KEYS.enemies.tinbackHauler,
  }),
  sparkWagon: Object.freeze({
    id: 'sparkWagon',
    name: 'Spark Wagon',
    maxHp: 116,
    speed: 66,
    reward: 14,
    stationDamage: 7,
    assetKey: ASSET_KEYS.enemies.sparkWagon,
  }),
  riftLeech: Object.freeze({
    id: 'riftLeech',
    name: 'Rift Leech',
    maxHp: 88,
    speed: 76,
    reward: 13,
    stationDamage: 6,
    assetKey: ASSET_KEYS.enemies.riftLeech,
    trait: Object.freeze({
      id: 'regeneration',
      label: 'Regenerates unless burning',
      description: 'Solar burn suppresses its regeneration.',
    }),
    regenPerSecond: 15,
    regenSuppressedBy: 'burn',
  }),
  siegeCrawler: Object.freeze({
    id: 'siegeCrawler',
    name: 'Siege Crawler',
    maxHp: 358,
    speed: 44,
    reward: 12,
    stationDamage: 14,
    assetKey: ASSET_KEYS.enemies.siegeCrawler,
  }),
  blackComet: Object.freeze({
    id: 'blackComet',
    name: 'The Black Comet',
    maxHp: 2480,
    speed: 40,
    reward: 200,
    stationDamage: 100,
    assetKey: ASSET_KEYS.enemies.blackComet,
  }),
});
