import { ASSET_KEYS } from '../assets/manifest.js';

export const ENEMY_DEFINITIONS = Object.freeze({
  dustMite: Object.freeze({
    id: 'dustMite',
    name: 'Dust Mite',
    maxHp: 28,
    speed: 92,
    reward: 5,
    nearbyXp: 3,
    heroKillXp: 12,
    attackDamage: 5,
    attackRange: 36,
    attackIntervalMs: 900,
    stationDamage: 2,
    assetKey: ASSET_KEYS.enemies.dustMite,
  }),
  rustRunner: Object.freeze({
    id: 'rustRunner',
    name: 'Rust Runner',
    maxHp: 48,
    speed: 138,
    reward: 6,
    nearbyXp: 4,
    heroKillXp: 16,
    attackDamage: 8,
    attackRange: 42,
    attackIntervalMs: 750,
    stationDamage: 4,
    assetKey: ASSET_KEYS.enemies.rustRunner,
  }),
  tinbackHauler: Object.freeze({
    id: 'tinbackHauler',
    name: 'Tinback Hauler',
    maxHp: 158,
    speed: 56,
    reward: 10,
    nearbyXp: 7,
    heroKillXp: 28,
    attackDamage: 14,
    attackRange: 38,
    attackIntervalMs: 1100,
    stationDamage: 9,
    assetKey: ASSET_KEYS.enemies.tinbackHauler,
  }),
  sparkWagon: Object.freeze({
    id: 'sparkWagon',
    name: 'Spark Wagon',
    maxHp: 116,
    maxShield: 48,
    speed: 66,
    reward: 12,
    nearbyXp: 6,
    heroKillXp: 24,
    attackDamage: 10,
    attackRange: 40,
    attackIntervalMs: 900,
    stationDamage: 7,
    assetKey: ASSET_KEYS.enemies.sparkWagon,
  }),
  riftLeech: Object.freeze({
    id: 'riftLeech',
    name: 'Rift Leech',
    maxHp: 88,
    speed: 76,
    reward: 13,
    nearbyXp: 5,
    heroKillXp: 22,
    attackDamage: 8,
    attackRange: 36,
    attackIntervalMs: 800,
    stationDamage: 6,
    assetKey: ASSET_KEYS.enemies.riftLeech,
    trait: Object.freeze({
      id: 'regeneration',
      label: 'Regenerates unless burning',
      description: 'Solar burn suppresses its regeneration.',
    }),
    regenPerSecond: 15,
    regenSuppressedBy: 'burn',
  }),
  siegeCrawler: Object.freeze({
    id: 'siegeCrawler',
    name: 'Siege Crawler',
    maxHp: 358,
    speed: 44,
    reward: 12,
    nearbyXp: 12,
    heroKillXp: 48,
    attackDamage: 18,
    attackRange: 42,
    attackIntervalMs: 1200,
    stationDamage: 14,
    assetKey: ASSET_KEYS.enemies.siegeCrawler,
  }),
  blackComet: Object.freeze({
    id: 'blackComet',
    name: 'The Black Comet',
    maxHp: 3780,
    speed: 40,
    reward: 200,
    nearbyXp: 48,
    heroKillXp: 200,
    attackDamage: 35,
    attackRange: 52,
    attackIntervalMs: 1000,
    stationDamage: 100,
    assetKey: ASSET_KEYS.enemies.blackComet,
  }),
});
